### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by ekin0116** [duzhaokun123/BilibiliHD2#7]
安装后打开显示未知错误
null
b9.a
	at c9.e.a(FailureResponseInterceptor.kt:31)
	at kd.f.c(RealInterceptorChain.kt:16)
	at c9.f.a(SortAndSignInterceptor.kt:58)
	at kd.f.c(RealInterceptorChain.kt:16)
	at c9.b.a(CommonParamInterceptor.kt:64)
	at kd.f.c(RealInterceptorChain.kt:16)
	at c9.a.a(CommonCookieInterceptor.kt:13)
	at kd.f.c(RealInterceptorChain.kt:16)
	at jd.e.h(RealCall.kt:25)
	at jd.e$a.run(RealCall.kt:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

**Comment by duzhaokun123** [comment]
装 debug 版或者说版本名

你这样没人救得了
