### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by RichardZhang4** [duzhaokun123/BilibiliHD2#83]
红米k20pro 安卓10
三星s8+ 安卓9
均无法打开

**Comment by RichardZhang4** [comment]
蓝奏云里9.8那个可用，但是提示有错误，如下
'''
null
b8.a
	at c8.f.a(FailureResponseInterceptor.kt:31)
	at mc.e.c(RealInterceptorChain.kt:16)
	at c8.g.a(SortAndSignInterceptor.kt:59)
	at mc.e.c(RealInterceptorChain.kt:16)
	at c8.c.a(CommonParamInterceptor.kt:64)
	at mc.e.c(RealInterceptorChain.kt:16)
	at c8.b.a(CommonHeaderInterceptor.kt:13)
	at mc.e.c(RealInterceptorChain.kt:16)
	at lc.e.i(RealCall.kt:25)
	at lc.e$a.run(RealCall.kt:11)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
'''

**Comment by RichardZhang4** [comment]
蓝奏云里9.8那个可用，但是提示有错误，如下
'''
null
b8.a
	at c8.f.a(FailureResponseInterceptor.kt:31)
	at mc.e.c(RealInterceptorChain.kt:16)
	at c8.g.a(SortAndSignInterceptor.kt:59)
	at mc.e.c(RealInterceptorChain.kt:16)
	at c8.c.a(CommonParamInterceptor.kt:64)
	at mc.e.c(RealInterceptorChain.kt:16)
	at c8.b.a(CommonHeaderInterceptor.kt:13)
	at mc.e.c(RealInterceptorChain.kt:16)
	at lc.e.i(RealCall.kt:25)
	at lc.e$a.run(RealCall.kt:11)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
'''
